use S3 Bucket to store the index.html

diff --git a/cloud-devops/projects/udagram/udagram.yml b/cloud-devops/projects/udagram/udagram.yml
--- a/cloud-devops/projects/udagram/udagram.yml
+++ b/cloud-devops/projects/udagram/udagram.yml
@@ -82,8 +82,16 @@ Resources:
               sudo apt-get install nginx -y
               sudo service nginx start
 
-              # Create a basic index.html file
-              echo "<h1>It works! Udagram, Udacity!</h1>" > /var/www/html/index.html
+              # Install the AWS CLI
+              sudo apt-get install awscli -y
+
+              # Download the index.html file from the S3 bucket, 
+              # Retry every 30 seconds until it succeeds to allow time for the S3 bucket to be created and the file to be uploaded
+              while !  sudo aws s3 cp s3://${ProjectName}-lazyinthegym-s3-bucket/index.html \
+              /var/www/html/index.html; \
+              do echo "Downloading index.html failed, retrying in 30 seconds..."; \
+              sleep 30; \
+              done
 
               # Copy the index.html file to the Nginx web directory
               sudo rm -r $WEB_DIR/index.*
@@ -212,3 +220,9 @@ Outputs:
     Value: !Sub "http://${WebAppLB.DNSName}"
     Export:
       Name: !Sub "${ProjectName}-LoadBalancerURL"
+  
+  S3BucketURL:
+    Description: "The S3 URI of the S3 Bucket"
+    Value: !Sub "s3://${S3Bucket}"
+    Export:
+      Name: !Sub "${ProjectName}-S3BucketURI"  
